#!/bin/sh

#SBATCH --job-name=BnB

#SBATCH --output=BnB.o

#SBATCH --error=BnB.error

#SBATCH --partition=savio

#SBATCH --time=400:00:00

#SBATCH --nodes=8

#SBATCH --ntasks-per-node=10

#SBATCH --cpus-per-task=2

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command

mpirun ~/bin/sss2/sss2_mpi BnB