#!/bin/sh

#SBATCH --job-name=BnB

#SBATCH --output=BnB.o

#SBATCH --error=BnB.error

#SBATCH --partition=savio2

#SBATCH --time=72:00:00

#SBATCH --nodes=8

#SBATCH --ntasks-per-node=14

#SBATCH --cpus-per-task=2

# QoS:

#SBATCH --qos=savio_normal

#

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command

mpirun ~/bin/sss2/sss2_mpi BnB