#!/bin/sh

#SBATCH --job-name=BnB11

#SBATCH --output=BnB.o

#SBATCH --error=BnB.error

#SBATCH --partition=savio2

#SBATCH --time=72:00:00

#SBATCH --nodes=4

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=20

# QoS:

#SBATCH --qos=savio_normal

#

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
setenv OMP_NUM_THREAD 20

mpirun -np 4 --map-by ppr:1:node:pe=20 ~/bin/sss2/sss2_mpi -omp 20 BnB